packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@hono/node-server": ^2.1.0
  "@lucide/vue": ^1.28.0
  "@types/node": ^24
  "@vitejs/plugin-vue": ^6.0.8
  antdv-next: ^1.4.6
  hono: ^4.13.0
  jsonc-parser: ^3.3.1
  puppeteer: ^25.8.0
  tsx: ^4.23.6
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
  vitest: ^4.1.10
  vue: ^3.5.40
  yaml: ^2.9.0
  zod: ^4.4.3
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  esbuild: true
  puppeteer: true
