/**
 * The Command Code GOAT subscription preset.
 *
 * Shipped snapshot of Command Code（commandcode.ai）的 GOAT 订阅：$10/月换约 $70 额度，
 * 通过 Provider API（OpenAI Chat Completions 兼容网关）以模型 API 原价计费，官方折扣
 * 自动生效。除 Go 之外的计划（GOAT / Pro / Max / Team）都带 API 访问权，用量按订阅
 * 额度计量；密钥在 Command Code Studio 的 API keys 页生成，只以 `$CMD_API_KEY` 引用。
 *
 * 模型与价格来自 GOAT 计划文档页（2026-09-07 抓取）：
 * https://commandcode.ai/docs/plans/goat 的模型表 + https://commandcode.ai/docs/reference/cli/models
 * 的模型 ID 目录。GOAT 目录无 Anthropic 模型，全部走 openai-completions 端点（Claude
 * 才需要 /messages）。价格为折扣后价格（MiniMax M3 五折、MiMo V2.5 最高 99% off、Laguna
 * S 2.1 / LongCat 2.0 免费），DeepSeek 为错峰价；`—` 的缓存写入档记 0。部分模型另设
 * 月度额度上限（如 GPT-5.6 Sol $70、DeepSeek V4 Flash $60，其余多为 $20），未逐条编码，
 * 导入后请对照官方文档核对。无上游刷新源，目录随代码更新。
 */
import type { ProviderPreset } from "./types.js";

export const commandCodeGoatDocsUrl = "https://commandcode.ai/docs/plans/goat";

export const commandCodeGoatPreset: ProviderPreset = {
  id: "command-code-goat",
  label: "Command Code GOAT",
  description:
    "Command Code 的 GOAT 订阅（$10/月 ≈ $70 额度，7 倍杠杆）。一个 OpenAI Chat Completions 兼容网关聚合 48 个开源与商用模型，按 API 原价从订阅额度计量、官方折扣自动生效；密钥在 Studio 的 API keys 页生成，设为 $CMD_API_KEY。GOAT 计划自带 Provider API 访问权（Go 计划除外）。",
  docsUrl: commandCodeGoatDocsUrl,
  provider: {
    baseUrl: "https://api.commandcode.ai/provider/v1",
    api: "openai-completions",
    apiKey: "$CMD_API_KEY",
  },
  models: [
    {
      id: "google/gemini-3.8-flash",
      name: "Gemini 3.8 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0 },
    },
    {
      id: "meta/muse-spark-1.3",
      name: "Muse Spark 1.3",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
    },
    {
      id: "meta/muse-spark-1.3-contributor",
      name: "Muse Spark 1.3 Contributor",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.8-Max-0902",
      name: "Qwen 3.8 Max 0902",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 0 },
    },
    {
      id: "tencent/hy4-preview",
      name: "Tencent Hy4 Preview",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.834, output: 2.501, cacheRead: 0.042, cacheWrite: 0 },
    },
    {
      id: "z-ai/glm-5.3-flash",
      name: "GLM-5.3 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.15, output: 0.5, cacheRead: 0.03, cacheWrite: 0 },
    },
    {
      id: "meituan/LongCat-2.0:free",
      name: "LongCat 2.0",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.8-Flash",
      name: "Qwen 3.8 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.16, output: 0.47, cacheRead: 0.016, cacheWrite: 0 },
    },
    {
      id: "deepseek/deepseek-v4-flash-fast",
      name: "DeepSeek V4 Flash Fast",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.28, output: 0.56, cacheRead: 0.07, cacheWrite: 0 },
    },
    {
      id: "deepseek/deepseek-v4-flash-vision-exp",
      name: "DeepSeek V4 Flash Vision (exp)",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.22, output: 0.66, cacheRead: 0.007, cacheWrite: 0 },
    },
    {
      id: "zai-org/GLM-5.3",
      name: "GLM-5.3",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.8-27B",
      name: "Qwen 3.8 27B",
      reasoning: true,
      input: ["text"],
      contextWindow: 262000,
      cost: { input: 0.4, output: 3, cacheRead: 0.04, cacheWrite: 0 },
    },
    {
      id: "deepseek/deepseek-v4-pro",
      name: "DeepSeek V4 Pro (latest)",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.66, output: 1.98, cacheRead: 0.022, cacheWrite: 0 },
    },
    {
      id: "google/gemini-3.7-flash",
      name: "Gemini 3.7 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 1.5, output: 7.5, cacheRead: 0.15, cacheWrite: 0.08334 },
    },
    {
      id: "xai/grok-4.6",
      name: "Grok 4.6",
      reasoning: true,
      input: ["text"],
      contextWindow: 500000,
      cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
    },
    {
      id: "meta/muse-spark-1.2",
      name: "Muse Spark 1.2",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 1.25, output: 4.25, cacheRead: 0.15, cacheWrite: 0 },
    },
    {
      id: "meta/muse-spark-1.2-contributor",
      name: "Muse Spark 1.2 Contributor",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.1, output: 0.2, cacheRead: 0.002, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.8-Max",
      name: "Qwen 3.8 Max",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 },
    },
    {
      id: "deepseek/deepseek-v4-flash",
      name: "DeepSeek V4 Flash (latest)",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.22, output: 0.66, cacheRead: 0.007, cacheWrite: 0 },
    },
    {
      id: "thinkingmachines/inkling-small",
      name: "Inkling Small",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.5, output: 1.2, cacheRead: 0.1, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.7-Flash",
      name: "Qwen 3.7 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.03, output: 0.13, cacheRead: 0.006, cacheWrite: 0.038 },
    },
    {
      id: "poolside/laguna-s-2.1-free",
      name: "Laguna S 2.1",
      reasoning: true,
      input: ["text"],
      contextWindow: 256000,
      cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    },
    {
      id: "thinkingmachines/inkling",
      name: "Inkling",
      reasoning: true,
      input: ["text"],
      contextWindow: 256000,
      cost: { input: 1, output: 4.05, cacheRead: 0.17, cacheWrite: 0 },
    },
    {
      id: "moonshotai/Kimi-K3",
      name: "Kimi K3",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
    },
    {
      id: "gpt-5.6-luna",
      name: "GPT-5.6 Luna",
      reasoning: true,
      input: ["text"],
      contextWindow: 1100000,
      cost: { input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25 },
    },
    {
      id: "gpt-5.6-sol",
      name: "GPT-5.6 Sol",
      reasoning: true,
      input: ["text"],
      contextWindow: 1100000,
      cost: { input: 5, output: 30, cacheRead: 0.5, cacheWrite: 6.25 },
    },
    {
      id: "xai/grok-4.5",
      name: "Grok 4.5",
      reasoning: true,
      input: ["text"],
      contextWindow: 500000,
      cost: { input: 2, output: 6, cacheRead: 0.5, cacheWrite: 0 },
    },
    {
      id: "tencent/hy3-paid",
      name: "Tencent Hy3",
      reasoning: true,
      input: ["text"],
      contextWindow: 262000,
      cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 },
    },
    {
      id: "zai-org/GLM-5.2-Fast",
      name: "GLM-5.2 Fast",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 3, output: 10.25, cacheRead: 0.5, cacheWrite: 0 },
    },
    {
      id: "zai-org/GLM-5.2",
      name: "GLM-5.2",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
    },
    {
      id: "moonshotai/Kimi-K2.7-Code-Highspeed",
      name: "Kimi K2.7 Code HighSpeed",
      reasoning: true,
      input: ["text"],
      contextWindow: 262000,
      cost: { input: 1.9, output: 8, cacheRead: 0.38, cacheWrite: 0 },
    },
    {
      id: "moonshotai/Kimi-K2.7-Code",
      name: "Kimi K2.7 Code",
      reasoning: true,
      input: ["text"],
      contextWindow: 256000,
      cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
    },
    {
      id: "nvidia/nemotron-3-ultra-550b-a55b",
      name: "Nemotron 3 Ultra",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.6, output: 2.4, cacheRead: 0.12, cacheWrite: 0 },
    },
    {
      id: "MiniMaxAI/MiniMax-M3",
      name: "MiniMax M3",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.7-Plus",
      name: "Qwen 3.7 Plus",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.4, output: 1.6, cacheRead: 0.08, cacheWrite: 0.5 },
    },
    {
      id: "stepfun/Step-3.7-Flash",
      name: "Step 3.7 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 256000,
      cost: { input: 0.2, output: 1.15, cacheRead: 0.04, cacheWrite: 0 },
    },
    {
      id: "xiaomi/mimo-v2.5",
      name: "MiMo V2.5",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
    },
    {
      id: "xiaomi/mimo-v2.5-pro",
      name: "MiMo V2.5 Pro",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.435, output: 0.87, cacheRead: 0.0036, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.7-Max",
      name: "Qwen 3.7 Max",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.13 },
    },
    {
      id: "stepfun/Step-3.5-Flash",
      name: "Step 3.5 Flash",
      reasoning: true,
      input: ["text"],
      contextWindow: 1000000,
      cost: { input: 0.1, output: 0.3, cacheRead: 0.02, cacheWrite: 0 },
    },
    {
      id: "zai-org/GLM-5.1",
      name: "GLM-5.1",
      reasoning: true,
      input: ["text"],
      contextWindow: 200000,
      cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
    },
    {
      id: "MiniMaxAI/MiniMax-M2.7",
      name: "MiniMax M2.7",
      reasoning: true,
      input: ["text"],
      contextWindow: 200000,
      cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
    },
    {
      id: "Qwen/Qwen3.6-Max-Preview",
      name: "Qwen 3.6 Max Preview",
      reasoning: true,
      input: ["text"],
      contextWindow: 200000,
      cost: { input: 1.3, output: 7.8, cacheRead: 0.26, cacheWrite: 1.63 },
    },
    {
      id: "Qwen/Qwen3.6-Plus",
      name: "Qwen 3.6 Plus",
      reasoning: true,
      input: ["text"],
      contextWindow: 200000,
      cost: { input: 0.5, output: 3, cacheRead: 0.1, cacheWrite: 0 },
    },
    {
      id: "moonshotai/Kimi-K2.6",
      name: "Kimi K2.6",
      reasoning: true,
      input: ["text"],
      contextWindow: 256000,
      cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 },
    },
    {
      id: "zai-org/GLM-5",
      name: "GLM-5",
      reasoning: true,
      input: ["text"],
      contextWindow: 200000,
      cost: { input: 1, output: 3.2, cacheRead: 0.2, cacheWrite: 0 },
    },
    {
      id: "moonshotai/Kimi-K2.5",
      name: "Kimi K2.5",
      reasoning: true,
      input: ["text"],
      contextWindow: 256000,
      cost: { input: 0.6, output: 3, cacheRead: 0.1, cacheWrite: 0 },
    },
    {
      id: "MiniMaxAI/MiniMax-M2.5",
      name: "MiniMax M2.5",
      reasoning: true,
      input: ["text"],
      contextWindow: 200000,
      cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 },
    },
  ],
};
