/**
 * Provider templates for Pi's `models.json`. These are starting points: connection fields
 * (base URL, API shape, key variable) are the durable part, while model IDs and prices move
 * whenever a vendor ships. Presets never carry a literal key — only a `$VAR_NAME` reference.
 *
 * Costs are US dollars per million tokens. Anthropic cache rates follow the published
 * multipliers: reads at 0.1x input, 5-minute writes at 1.25x input.
 */
import type { ProviderPreset } from "../adapters/types.js";

export const piModelPresets: ProviderPreset[] = [
  {
    id: "anthropic",
    label: "Anthropic",
    description: "Claude 官方 API，Messages 接口。",
    docsUrl: "https://platform.claude.com/docs/en/about-claude/models/overview",
    provider: {
      baseUrl: "https://api.anthropic.com/v1",
      api: "anthropic-messages",
      apiKey: "$ANTHROPIC_API_KEY",
    },
    models: [
      {
        id: "claude-opus-5",
        name: "Claude Opus 5",
        contextWindow: 1000000,
        maxTokens: 128000,
        input: ["text", "image"],
        reasoning: true,
        cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
      },
      {
        id: "claude-sonnet-5",
        name: "Claude Sonnet 5",
        contextWindow: 1000000,
        maxTokens: 128000,
        input: ["text", "image"],
        reasoning: true,
        cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
      },
      {
        id: "claude-haiku-4-5",
        name: "Claude Haiku 4.5",
        contextWindow: 200000,
        maxTokens: 64000,
        input: ["text", "image"],
        reasoning: true,
        cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
      },
      {
        id: "claude-fable-5",
        name: "Claude Fable 5",
        contextWindow: 1000000,
        maxTokens: 128000,
        input: ["text", "image"],
        reasoning: true,
        cost: { input: 10, output: 50, cacheRead: 1, cacheWrite: 12.5 },
      },
    ],
  },
  {
    id: "deepseek",
    label: "DeepSeek",
    description: "DeepSeek 官方 API，OpenAI Chat Completions 兼容。",
    docsUrl: "https://api-docs.deepseek.com",
    provider: {
      baseUrl: "https://api.deepseek.com",
      api: "openai-completions",
      apiKey: "$DEEPSEEK_API_KEY",
    },
    models: [
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        contextWindow: 1000000,
        maxTokens: 384000,
        input: ["text"],
        reasoning: true,
        cost: { input: 1.74, output: 3.48, cacheRead: 0.145, cacheWrite: 0 },
        compat: {
          requiresReasoningContentOnAssistantMessages: true,
          thinkingFormat: "deepseek",
          reasoningEffortMap: {
            minimal: "high",
            low: "high",
            medium: "high",
            high: "high",
            xhigh: "max",
          },
        },
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        contextWindow: 1000000,
        maxTokens: 384000,
        input: ["text"],
        reasoning: true,
        cost: { input: 0.14, output: 0.28, cacheRead: 0.028, cacheWrite: 0 },
        compat: {
          requiresReasoningContentOnAssistantMessages: true,
          thinkingFormat: "deepseek",
          reasoningEffortMap: {
            minimal: "high",
            low: "high",
            medium: "high",
            high: "high",
            xhigh: "max",
          },
        },
      },
    ],
  },
  {
    id: "ark",
    label: "火山方舟 Coding",
    description: "字节火山引擎方舟的 Coding 端点，聚合豆包与多家第三方模型。",
    docsUrl: "https://www.volcengine.com/docs/82379",
    provider: {
      baseUrl: "https://ark.cn-beijing.volces.com/api/coding/v3",
      api: "openai-responses",
      apiKey: "$ARK_API_KEY",
    },
    models: [
      {
        id: "doubao-seed-2.0-code",
        name: "Doubao Seed 2.0 Code",
        contextWindow: 256000,
        input: ["text"],
        reasoning: true,
      },
      {
        id: "doubao-seed-2.0-pro",
        name: "Doubao Seed 2.0 Pro",
        contextWindow: 256000,
        input: ["text"],
        reasoning: true,
      },
      { id: "kimi-k2.7-code", name: "Kimi K2.7 Code", input: ["text"], reasoning: true },
      { id: "glm-latest", name: "GLM Latest", input: ["text"], reasoning: true },
    ],
  },
  {
    id: "opencode-go",
    label: "OpenCode Go",
    description:
      "OpenCode 的低成本开源编程模型订阅服务（首月 $5，之后 $10/月）。统一网关下聚合多家开源模型，按模型自动路由到 Chat Completions、Responses 或 Messages 接口；密钥在 OpenCode Zen 控制台获取，设为 $OPENCODE_API_KEY。",
    docsUrl: "https://opencode.ai/docs/zh-cn/go/",
    provider: {
      baseUrl: "https://opencode.ai/zen/go/v1",
      api: "openai-completions",
      apiKey: "$OPENCODE_API_KEY",
    },
    models: [
      {
        id: "grok-4.5",
        name: "Grok 4.5",
        reasoning: true,
        input: ["text"],
        cost: { input: 2, output: 6, cacheRead: 0.3, cacheWrite: 0 },
      },
      {
        id: "glm-5.2",
        name: "GLM-5.2",
        reasoning: true,
        input: ["text"],
        cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
      },
      {
        id: "glm-5.1",
        name: "GLM-5.1",
        reasoning: true,
        input: ["text"],
        cost: { input: 1.4, output: 4.4, cacheRead: 0.26, cacheWrite: 0 },
      },
      {
        id: "kimi-k3",
        name: "Kimi K3",
        reasoning: true,
        input: ["text"],
        cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 0 },
      },
      {
        id: "kimi-k2.7-code",
        name: "Kimi K2.7 Code",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.95, output: 4, cacheRead: 0.19, cacheWrite: 0 },
      },
      {
        id: "kimi-k2.6",
        name: "Kimi K2.6",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.95, output: 4, cacheRead: 0.16, cacheWrite: 0 },
      },
      {
        id: "deepseek-v4-pro",
        name: "DeepSeek V4 Pro",
        reasoning: true,
        input: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        cost: { input: 0.435, output: 0.87, cacheRead: 0.003625, cacheWrite: 0 },
      },
      {
        id: "deepseek-v4-flash",
        name: "DeepSeek V4 Flash",
        reasoning: true,
        input: ["text"],
        contextWindow: 1000000,
        maxTokens: 384000,
        cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
      },
      {
        id: "mimo-v2.5",
        name: "MiMo V2.5",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.14, output: 0.28, cacheRead: 0.0028, cacheWrite: 0 },
      },
      {
        id: "mimo-v2.5-pro",
        name: "MiMo V2.5 Pro",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.435, output: 0.87, cacheRead: 0.003625, cacheWrite: 0 },
      },
      {
        id: "hy3",
        name: "Hy3",
        reasoning: true,
        input: ["text"],
        cost: { input: 0.14, output: 0.58, cacheRead: 0.035, cacheWrite: 0 },
      },
      {
        id: "gpt-5.6-luna",
        name: "GPT 5.6 Luna",
        reasoning: true,
        input: ["text"],
        api: "openai-responses",
        contextWindow: 272000,
        cost: {
          input: 0.2,
          output: 1.2,
          cacheRead: 0.02,
          cacheWrite: 0.25,
          tiers: [
            {
              inputTokensAbove: 272000,
              input: 0.4,
              output: 1.8,
              cacheRead: 0.04,
              cacheWrite: 0.5,
            },
          ],
        },
      },
      {
        id: "minimax-m3",
        name: "MiniMax M3",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0 },
      },
      {
        id: "minimax-m2.7",
        name: "MiniMax M2.7",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0.375 },
      },
      {
        id: "minimax-m2.5",
        name: "MiniMax M2.5",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: { input: 0.3, output: 1.2, cacheRead: 0.06, cacheWrite: 0.375 },
      },
      {
        id: "qwen3.8-max",
        name: "Qwen3.8 Max",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: { input: 2, output: 6, cacheRead: 0.25, cacheWrite: 2.5 },
      },
      {
        id: "qwen3.7-max",
        name: "Qwen3.7 Max",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: { input: 2.5, output: 7.5, cacheRead: 0.5, cacheWrite: 3.125 },
      },
      {
        id: "qwen3.7-plus",
        name: "Qwen3.7 Plus",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: {
          input: 0.4,
          output: 1.6,
          cacheRead: 0.04,
          cacheWrite: 0.5,
          tiers: [
            {
              inputTokensAbove: 256000,
              input: 1.2,
              output: 4.8,
              cacheRead: 0.12,
              cacheWrite: 1.5,
            },
          ],
        },
      },
      {
        id: "qwen3.6-plus",
        name: "Qwen3.6 Plus",
        reasoning: true,
        input: ["text"],
        api: "anthropic-messages",
        cost: {
          input: 0.5,
          output: 3,
          cacheRead: 0.05,
          cacheWrite: 0.625,
          tiers: [
            {
              inputTokensAbove: 256000,
              input: 2,
              output: 6,
              cacheRead: 0.2,
              cacheWrite: 2.5,
            },
          ],
        },
      },
    ],
  },
  {
    id: "openai",
    label: "OpenAI",
    description: "OpenAI 官方 API，Responses 接口。模型目录请按账号可用范围自行添加。",
    docsUrl: "https://platform.openai.com/docs/models",
    provider: {
      baseUrl: "https://api.openai.com/v1",
      api: "openai-responses",
      apiKey: "$OPENAI_API_KEY",
    },
    models: [],
  },
  {
    id: "google",
    label: "Google Gemini",
    description: "Google Generative AI 接口。模型目录请按账号可用范围自行添加。",
    docsUrl: "https://ai.google.dev/gemini-api/docs/models",
    provider: {
      baseUrl: "https://generativelanguage.googleapis.com/v1beta",
      api: "google-generative-ai",
      apiKey: "$GEMINI_API_KEY",
    },
    models: [],
  },
  {
    id: "openrouter",
    label: "OpenRouter",
    description: "OpenRouter 聚合网关，模型 ID 形如 vendor/model。",
    docsUrl: "https://openrouter.ai/docs",
    provider: {
      baseUrl: "https://openrouter.ai/api/v1",
      api: "openai-completions",
      apiKey: "$OPENROUTER_API_KEY",
    },
    models: [],
  },
  {
    id: "ollama",
    label: "Ollama（本地）",
    description: "本地 Ollama 服务，不需要密钥；模型 ID 用 ollama list 里的 tag。",
    docsUrl: "https://github.com/ollama/ollama/blob/main/docs/openai.md",
    provider: {
      baseUrl: "http://localhost:11434/v1",
      api: "openai-completions",
    },
    models: [],
  },
];
