import Alert from "antdv-next/dist/alert/index";
import Avatar from "antdv-next/dist/avatar/index";
import Badge from "antdv-next/dist/badge/index";
import Breadcrumb, { BreadcrumbItem } from "antdv-next/dist/breadcrumb/index";
import Button from "antdv-next/dist/button/index";
import Card from "antdv-next/dist/card/index";
import Checkbox from "antdv-next/dist/checkbox/index";
import Collapse, { CollapsePanel } from "antdv-next/dist/collapse/index";
import ConfigProvider from "antdv-next/dist/config-provider/index";
import Divider from "antdv-next/dist/divider/index";
import Drawer from "antdv-next/dist/drawer/index";
import Form, { FormItem } from "antdv-next/dist/form/index";
import Empty from "antdv-next/dist/empty/index";
import { Col, Row } from "antdv-next/dist/grid/index";
import Input, { InputPassword } from "antdv-next/dist/input/index";
import InputNumber from "antdv-next/dist/input-number/index";
import Layout, {
  LayoutContent,
  LayoutFooter,
  LayoutHeader,
  LayoutSider,
} from "antdv-next/dist/layout/index";
import Menu, { MenuItem } from "antdv-next/dist/menu/index";
import Modal from "antdv-next/dist/modal/index";
import Popconfirm from "antdv-next/dist/popconfirm/index";
import Segmented from "antdv-next/dist/segmented/index";
import Select, { SelectOption } from "antdv-next/dist/select/index";
import Space from "antdv-next/dist/space/index";
import Spin from "antdv-next/dist/spin/index";
import Switch from "antdv-next/dist/switch/index";
import Table from "antdv-next/dist/table/index";
import Tag from "antdv-next/dist/tag/index";
import Tooltip from "antdv-next/dist/tooltip/index";
import Typography from "antdv-next/dist/typography/index";
import { createApp } from "vue";
import "antdv-next/dist/reset.css";
import App from "./App.vue";
import "./style.css";

const app = createApp(App);
app.component("AAlert", Alert);
app.component("AAvatar", Avatar);
app.component("ABadge", Badge);
app.component("ABreadcrumb", Breadcrumb);
app.component("ABreadcrumbItem", BreadcrumbItem);
app.component("AButton", Button);
app.component("ACard", Card);
app.component("ACheckbox", Checkbox);
app.component("ACollapse", Collapse);
app.component("ACollapsePanel", CollapsePanel);
app.component("AConfigProvider", ConfigProvider);
app.component("ADivider", Divider);
app.component("ADrawer", Drawer);
app.component("AForm", Form);
app.component("AFormItem", FormItem);
app.component("AEmpty", Empty);
app.component("ACol", Col);
app.component("ARow", Row);
app.component("AInput", Input);
app.component("AInputPassword", InputPassword);
app.component("AInputNumber", InputNumber);
app.component("ALayout", Layout);
app.component("ALayoutContent", LayoutContent);
app.component("ALayoutFooter", LayoutFooter);
app.component("ALayoutHeader", LayoutHeader);
app.component("ALayoutSider", LayoutSider);
app.component("AMenu", Menu);
app.component("AMenuItem", MenuItem);
app.component("AModal", Modal);
app.component("APopconfirm", Popconfirm);
app.component("ASegmented", Segmented);
app.component("ASelect", Select);
app.component("ASelectOption", SelectOption);
app.component("ASpace", Space);
app.component("ASpin", Spin);
app.component("ASwitch", Switch);
app.component("ATable", Table);
app.component("ATag", Tag);
app.component("ATooltip", Tooltip);
app.component("ATypographyText", Typography.Text);
app.component("ATypographyTitle", Typography.Title);
app.mount("#app");
